In [5]:
import os
import tensorflow
import pandas as pd
import numpy as np
import seaborn as sns
from tqdm import tqdm
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
from matplotlib.image import imread
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Flatten, Dense, Conv2D, MaxPooling2D
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.preprocessing import image
from sklearn.metrics import classification_report, confusion_matrix
import tensorflow_hub as hub

In [6]:
def testmalaria(img):
    malaria_model = tensorflow.keras.models.load_model("./models/malaria.h5")
    image_shape = (130,130,3)
    new_image = tensorflow.keras.preprocessing.image.load_img(img, target_size=image_shape)
    new_image = image.img_to_array(new_image)
    new_image = np.expand_dims(new_image, axis=0)
    result = malaria_model.predict(new_image)
    if(result[0]):
        return "positive for malaria"
    else:
        return "negative for malaria"
    

In [7]:
def testcancer(img1):
    IMG_SIZE = 128
    img1 = tensorflow.reshape(img1, [])
    img = tensorflow.io.read_file(img1)
    img = tensorflow.io.decode_bmp(img, channels=3)
    print(img)
    img = tensorflow.image.resize(img, [IMG_SIZE,IMG_SIZE])
    img = np.expand_dims(img, axis=0)
    cancer_model = tensorflow.keras.models.load_model(('./models/cancer.h5'),custom_objects={'KerasLayer':hub.KerasLayer})
    prediction = cancer_model.predict(img)
    print(prediction)
    prediction = np.argmax(prediction,axis=1)
    if (prediction == 0):
        result = "positive for blood cancer (acute lymphocytic leukaemia)"
        return result
    else:
        result = "negative for blood cancer (acute lymphocytic leukaemia)"
        return result

In [8]:
img = "./3.bmp"

In [9]:
testcancer(img)

tf.Tensor(
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], shape=(450, 450, 3), dtype=uint8)
[[0. 1.]]


'negative for blood cancer (acute lymphocytic leukaemia)'